"AMDOpenCLDeviceDetection.exe -p" > debug_all_out.txt
AMDOpenCLDeviceDetection.exe -p >> debug_all_out.txt
"CudaDeviceDetection.exe -p" >> debug_all_out.txt
CudaDeviceDetection.exe -p >> debug_all_out.txt
"bin\ccminer_decred\ccminer -n" >> debug_all_out.txt
bin\ccminer_decred\ccminer -n >> debug_all_out.txt
"bin\ccminer_nanashi\ccminer -n" >> debug_all_out.txt
bin\ccminer_nanashi\ccminer -n >> debug_all_out.txt
"bin\ccminer_tpruvot\ccminer -n" >> debug_all_out.txt
bin\ccminer_tpruvot\ccminer -n >> debug_all_out.txt
