namespace zPoolMiner.Enums
{
    public enum MinerType
    {
        NONE,
        ccminer,
        ccminer_CryptoNight,
        ethminer_OCL,
        ethminer_CUDA,
        sgminer,
        glg,
        cpuminer_opt,
        nheqminer_CPU,
        nheqminer_CUDA,
        nheqminer_AMD,
        eqm_CPU,
        eqm_CUDA,
        ClaymoreZcash,
        ClaymoreCryptoNight,
        OptiminerZcash,
        excavator,
        ClaymoreDual,
        EWBF,
        DSTM,
        Xmrig,
        hsrneoscrypt,
        //hsrneoscrypt_hsr,
        //mkxminer,
        END
    }
}
